### ISSUE TITLE
add an optional portainer compose

### ISSUE THREAD

**Issue by artmg** [artmg/home-assistant-docker#5]
example portainer docker-compose.yaml
```
version: '3'
services:
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    restart: always
```
